name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allow manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and test each day subproject
      run: |
        for dir in day*/; do
          if [ -d "$dir" ]; then
            echo "Building and testing $dir"
            cd "$dir"
            cargo build --verbose
            cargo test --verbose
            cd ..
          fi
        done

